services:
  dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ui-builder
    
    # Maps Next.js port 3000 from host to container
    ports:
      - "3000:3000"

    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0 # Ensures Next.js binds to all interfaces for network access