services:
  ui-builder:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: ui-builder
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /app
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0 # Ensures Next.js binds to all interfaces for network access
